"""empty message

Revision ID: 389c487c8880
Revises: 830cc6a5a4a3
Create Date: 2022-06-21 10:51:58.447767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '389c487c8880'
down_revision = '830cc6a5a4a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('birth_year', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'birth_year')
    # ### end Alembic commands ###
