"""empty message

Revision ID: 5fd7c2345231
Revises: 7a6f206a2da4
Create Date: 2022-06-23 12:21:43.298873

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5fd7c2345231'
down_revision = '7a6f206a2da4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'cargo_capacity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('cargo_capacity', mysql.VARCHAR(length=250), nullable=True))
    # ### end Alembic commands ###
