"""empty message

Revision ID: 68226cfb5cc8
Revises: 791d0cef4827
Create Date: 2022-06-21 10:44:23.022241

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '68226cfb5cc8'
down_revision = '791d0cef4827'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'specie')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('specie', mysql.VARCHAR(length=250), nullable=True))
    # ### end Alembic commands ###
