"""empty message

Revision ID: 7a6f206a2da4
Revises: c568996a0c82
Create Date: 2022-06-23 12:19:45.189000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a6f206a2da4'
down_revision = 'c568996a0c82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('vehicle_class', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'vehicle_class')
    # ### end Alembic commands ###
