"""empty message

Revision ID: 7c01ff88fc91
Revises: 5fd7c2345231
Create Date: 2022-06-23 12:22:15.671952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c01ff88fc91'
down_revision = '5fd7c2345231'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('cargo_capacity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'cargo_capacity')
    # ### end Alembic commands ###
