"""empty message

Revision ID: 9650adfbd411
Revises: 389c487c8880
Create Date: 2022-06-22 19:06:19.531400

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9650adfbd411'
down_revision = '389c487c8880'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planets', 'climate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('climate', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
