"""empty message

Revision ID: c568996a0c82
Revises: f71ff1533f8d
Create Date: 2022-06-23 12:18:11.584160

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c568996a0c82'
down_revision = 'f71ff1533f8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'vehicle_class')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('vehicle_class', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
