"""empty message

Revision ID: f71ff1533f8d
Revises: 9650adfbd411
Create Date: 2022-06-22 19:06:56.585197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f71ff1533f8d'
down_revision = '9650adfbd411'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('climate', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planets', 'climate')
    # ### end Alembic commands ###
